### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by lsetiawan** [Ciela-Institute/caustics#117]
I notice that there are a total of [29 branches](https://github.com/Ciela-Institute/caustics/branches/all) and a lot of them are [stale](https://github.com/Ciela-Institute/caustics/branches/stale). I think it would be good to clean this up so that users doesn't get confused and it looks cleaner too 😄

**Comment by ConnorStoneAstro** [comment]
All branches with no content have been purged. Next I'll go through the remaining ones to see which get to live

**Comment by ConnorStoneAstro** [comment]
Ok, I've purged all branches that have fallen too far behind. The remaining ones have content to be considered / are in active development.

**Comment by lsetiawan** [comment]
Thanks @ConnorStoneAstro! I'll consider this as DONE.
