### ISSUE TITLE
Caustics import

### ISSUE THREAD

**Issue by AlexandreAdam** [Ciela-Institute/caustics#154]
I would like to be able to imports modules from caustics in the following way

```python
from caustics import NFW, FlatLambdaCDM
```

(like it was before v0.7.0 I believe)

rather than the current way

```python
from caustics.lenses import NFW
from caustics.cosmology import FlatLambdaCDM
```

The first way is more convenient, especially if I already know what I want from the caustics. Also, the first approach is very reminiscent of how somebody use functions from torch or numpy. Often one can simply import numpy and get all the function he needs from the root of the package rather than having to import many submodule, which worsen the user experience and makes it much less intuitive.

**Comment by ConnorStoneAstro** [comment]
Closed by #155
