### ISSUE TITLE
Should external shear convergence be zeros?

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Ciela-Institute/caustics#199]
Currently throws an error

**Comment by AlexandreAdam** [comment]
Yes, by definition external convergence is 0. In #196 I define the external convergence to be zero. See also the derivation of the external convergence by Meneghetti. 

By construction, the external convergence only produce a shear, so the Jacobian matrix of the lens equation must have zero on its diagonal by construction.

**Comment by ConnorStoneAstro** [comment]
Solved in #191
