### ISSUE TITLE
JOSS Review: Mention Herculens

### ISSUE THREAD

**Issue by Jammy2211** [Ciela-Institute/caustics#263]
Can the JOSS paper be updated to specifically refer to Herculens (https://github.com/Herculens/herculens?tab=readme-ov-file) in the the second paragraph of the "statement of need" section. 

This software uses JAX and is probably the closest open source package to `caustics`, albeit I don't see dedication documentation for lensing simulations.

**Comment by ConnorStoneAstro** [comment]
Thanks! I'll make sure it's in the updated version

**Comment by ConnorStoneAstro** [comment]
Indeed, Herculens is an excellent addition to the literature review at the beginning of the paper. We have added a citation to the statement of need section alongside the other lensing codes. You can see the updated draft in the [JOSS review page](https://github.com/openjournals/joss-reviews/issues/7081). Please let me know if there is anything else you think we should comment on!
