### ISSUE TITLE
torchinterp1d and KeOps are incompatible with vmap

### ISSUE THREAD

**Issue by adam-coogan** [Ciela-Institute/caustics#30]
`vmap` is not compatible with `torchinterp1d` or `keops`. Both use `torch.autograd.Function`, which is not compatible with `vmap` by default. This will be a problem if you want to e.g. `vmap` over a bunch of `NFW`s for simulating or computing magnifications, since they may use `torchinterp1d` via `FlatLambdaCDM`. [This is fixable](https://pytorch.org/docs/stable/notes/extending.func.html#torch-vmap-support), but requires modifying `torchinterp1d` and `keops`. I've opened issues in [both](https://github.com/aliutkus/torchinterp1d/issues/20) projects' [repos](https://github.com/getkeops/keops/issues/303).

This isn't really our responsibility to fix, but I wanted to document this since it's good to be aware of this restriction.

**Comment by ConnorStoneAstro** [comment]
We no longer depend on torchinterp1d and only have limited compatibility with keops. It would be good to open another issue specifically for keops compatibility.
