### ISSUE TITLE
Built-in source samplers 

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Ciela-Institute/caustics#32]
For prototyping it would be useful to have a caustic built-in system to sample reasonable source images. The github could store the PROBES sample and there could be a method in caustic to draw a random PROBES galaxy. This would download an HDF5 file (first time its called) with the PROBES sample, then randomly select one, and sample it at the desired resolution.

**Comment by adam-coogan** [comment]
I'd recommend using the functionality already built into torch for this kind of thing: in particular `Dataset`s for storing the data and `DataLoader`s for iterating through the data in various ways. And actually, I've already written one for HDF5 files as well as PROBES and Illustris-specific datasets that should cover a fair chunk of what's needed.

The main missing piece compared to what you're suggesting is downloading functionality. For consistency, I'd take a look at the [`MNIST` dataset](https://pytorch.org/vision/stable/_modules/torchvision/datasets/mnist.html#MNIST) in torchvision, which has an init argument indicating whether or not to download the dataset.

**Comment by ConnorStoneAstro** [comment]
On further reflection this seems like it would add unnecessary complexity where caustics is trying to be lean. Happy to revisit, but for now I don't think this is on the development path
