### ISSUE TITLE
autograd through NFW deflection angles returns NAN

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Ciela-Institute/caustics#69]
When testing multiplane with NFW lenses, I noticed that I get nans when trying to do autograd through them. This doesn't happen with pseudojaffe or other lenses.

**Comment by AlexandreAdam** [comment]
There seem to be some numerical instability going on. If we fix this issue we should fix [Issue 45](https://github.com/Ciela-Institute/caustic/issues/45) at the same time.

**Comment by ConnorStoneAstro** [comment]
After completing the TNFW lens in #74 I believe the issue is that some operations for the NFW need to be done in the complex plane. Once this was added for the TNFW it became more stable and autograd started working

**Comment by ConnorStoneAstro** [comment]
Closed by #83
