### ISSUE TITLE
Units in docs

### ISSUE THREAD

**Issue by ConnorStoneAstro** [Ciela-Institute/caustics#78]
All our functions should specify the units for inputs and outputs. It can be very frustrating trying to do anything exact without knowing the expected units for a function. In some cases the units are arbitrary and will just be passed along as given, in that case we can explicitly state that so at least it is clear.

**Comment by lsetiawan** [comment]
@uwcdc and I had discussion yesterday that one solution potentially can be this format for example:

```rst
Parameters
----------
x : type
    Description of parameter `x`.

    *Unit: unitless*  
```

Having it in that way seems nice because it's very clear and the italics rendering makes it stand out a bit more.
